# Generated by Django 5.1.3 on 2024-11-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_watchesuploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchesuploads',
            name='image',
            field=models.ImageField(upload_to='Watches_images/'),
        ),
    ]
