# Generated by Django 5.1.3 on 2024-12-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_watchreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchreview',
            name='review_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='watchreview',
            name='rating',
            field=models.PositiveBigIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
